---
title: "Training features from MIA samples"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Feb 14, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Summary

+ In this document, the CPOP feature selection is done between MIA-microarray and MIA-NS. Bootstrap is used to induce variability in the training data. We will output a RData file with all the features. 


# Loading 

## Packages

```{r}
today = format(Sys.time(), "%Y_%b_%d")
cat("This file was compiled on", today)


suppressPackageStartupMessages({
  library(tidyverse)
  library(CPOP)
  library(glmnet)
  library(yardstick)
  library(ggbeeswarm)
  library(survival)
  library(survminer)
})

theme_set(theme_classic(12) +
            theme(legend.position = "bottom"))
```


## data

```{r}
file_version = "2020_Apr_25"
load(paste0(
  "../data/processed_data/Melanoma4_binary_",
  file_version, ".RData"
))


load(paste0(
  "../data/processed_data/Melanoma4_survival_",
  file_version, ".RData"
))
```

# Construct logratio matrices
```{r}
list_raw_data_binary = list_raw_data_binary %>% purrr::map(t)

list_lratio_binary = purrr::map(list_raw_data_binary, CPOP::pairwise_col_diff)

list_lratio_data_survival = list_raw_data %>%
  purrr::map(t) %>%
  purrr::map(CPOP::pairwise_col_diff)

sapply(list_raw_data_binary, dim)
sapply(list_lratio_binary, dim)
sapply(list_lratio_data_survival, dim)
```


# Single run of CPOP to illustrate 

```{r}
set.seed(123)

single_cpop = CPOP::cpop_model(
  z1 = list_lratio_binary$ns,
  z2 = list_lratio_binary$array,
  y1 = list_binary_lassoy$ns,
  y2 = list_binary_lassoy$array,
  family = "binomial",
  alpha = 0.1,
  n_features = 20)

single_cpop

CPOP::plot_cpop(single_cpop, type = "ggraph")
```

## Prediction
```{r}
CPOP::predict_cpop(cpop_result = single_cpop,
                   newz = list_lratio_binary$tcga,
                   s = "lambda.min") %>% 
  left_join(list_binary_lassoy_df, by = c("samples" = "sample_id")) %>% 
  ggplot(aes(x = classification, y = CPOP::expit(cpop_model_avg))) +
  geom_boxplot() +
  geom_hline(yintercept = 0.5, col = "red") +
  geom_jitter(width = 0.2)
```



# Bootstrap samples
```{r, message=FALSE}
set.seed(123)
nexp = 100

ns_index = replicate(nexp, sample(1:nrow(list_lratio_binary$ns), size = 100, replace = TRUE), simplify = FALSE)
array_index = replicate(nexp, sample(1:nrow(list_lratio_binary$array), size = 100, replace = TRUE), simplify = FALSE)

resample_lratio_ns = purrr::map(.x = ns_index, .f = ~ list_lratio_binary$ns[.x,])
resample_lratio_array = purrr::map(.x = array_index, .f = ~ list_lratio_binary$array[.x,])
resample_lassoy_ns = purrr::map(.x = ns_index, .f = ~ list_binary_lassoy$ns[.x])
resample_lassoy_array = purrr::map(.x = array_index, .f = ~ list_binary_lassoy$array[.x])
# resample_w = purrr::map2(.x = resample_lratio_ns, 
#                          .y = resample_lratio_array,
#                          .f = CPOP::compute_weights)


# boot_MIA_cpop = mapply(
boot_MIA_cpop = parallel::mcmapply(
  FUN = CPOP::cpop_model,
  z1 = resample_lratio_ns,
  y1 = resample_lassoy_ns, 
  z2 = resample_lratio_array, 
  y2 = resample_lassoy_array, 
  # w = resample_w,
  family = "binomial",
  alpha = 0.1,
  n_features = 50, 
  nfolds = 5,
  SIMPLIFY = FALSE,
  mc.cores = 5)

boot_MIA_ns = parallel::mcmapply(
  FUN = cv.glmnet,
  x = resample_lratio_ns,
  y = resample_lassoy_ns, 
  family = "binomial",
  alpha = 1,
  nfolds = 5,
  SIMPLIFY = FALSE,
  mc.cores = 5)

boot_MIA_array = parallel::mcmapply(
  FUN = cv.glmnet,
  x = resample_lratio_array,
  y = resample_lassoy_array, 
  family = "binomial",
  alpha = 1,
  nfolds = 5,
  SIMPLIFY = FALSE,
  mc.cores = 5)


save(boot_MIA_cpop,
     boot_MIA_ns,
     boot_MIA_array,
     file = paste0("../data/processed_data/boot_MIA_cpop_", today, ".RData"))
```

# Session info 
```{r}
sessioninfo::session_info()
```

