---
title: "MIA - March validation 60 samples data cleaning"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Feb 16, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---


# Summary


# Loading 

## Packages

```{r}
today = format(Sys.time(), "%Y_%b_%d")
cat("This file was compiled on", today)


suppressPackageStartupMessages({
  library(tidyverse)
  library(NanoStringQCPro)
  library(survminer)
  library(survival)
  library(ggsci)
  library(janitor)
})

theme_set(theme_classic(20) +
            theme(legend.position = "bottom"))

boxplot_tbl = function(x, index = 1){
  means = apply(x, index, mean, na.rm = TRUE)
  medians = apply(x, index, median, na.rm = TRUE)
  q1 = apply(x, index, quantile, 0.25, na.rm = TRUE)
  q3 = apply(x, index, quantile, 0.75, na.rm = TRUE)
  
  tbl = tibble(
    object = as_factor(dimnames(x)[[index]]),
    means, medians, q1, q3)
  
  return(tbl)
}

```



## Raw NanoString data
```{r}
rcc_files = list.files("../data/raw_data/validation60_15_March_2020/", 
                       recursive = TRUE, full.names = TRUE,
                       pattern = "[.]RCC")

ns_v60_data = newRccSet(rccFiles = rcc_files,
                        rlf ="../data/raw_data/Pupo_1_C12874.RLF")


cat("If the following dimensions match with the number of RCC files above, then we have read in all files properly.")
dim(ns_v60_data)
stopifnot(ncol(ns_v60_data) == length(rcc_files))
```

## Previous 45 samples  
```{r}
file_version = "2020_Apr_25"
load(paste0(
  "../data/processed_data/Melanoma4_binary_",
  file_version, ".RData"
))

load(paste0(
  "../data/processed_data/Melanoma4_survival_",
  file_version, ".RData"
))
```


# Processing sample, feature, exprs data for NanoString (commented out to run only once)


## Feature data

+ We will extract the gene probes data to ease the processing. 

```{r}
ns_feature_data = fData(ns_v60_data) %>% 
  janitor::clean_names()

ns_all_genes = ns_feature_data$gene_name

ns_endo_genes = ns_feature_data %>% 
  dplyr::filter(code_class == "Endogenous") %>% 
  dplyr::pull(gene_name)

ns_hk_genes = ns_feature_data %>% 
  dplyr::filter(code_class == "Housekeeping") %>% 
  dplyr::pull(gene_name)

# nsHkGenes = c("RERE", "CENPB", "CTBP1", "GNB2L1", "SNRPD2", "UQCR")
```


## Sample data 


```{r}
ns_v60_raw_sample_data = pData(ns_v60_data) %>% 
  janitor::clean_names() %>% 
  dplyr::mutate(date = lubridate::ymd(date),
                cartridge_id = as.character(cartridge_id),
                sample_id = trimws(sample_id)) %>% 
  remove_empty("cols") %>% as_tibble()

ns_v60_raw_sample_data %>% glimpse()

## One of the samples had a mis-label. See May 18 email by GP and KW, https://trello.com/c/sizkc4Ku. 
ns_v60_raw_sample_data = ns_v60_raw_sample_data %>% 
  dplyr::mutate(sample_id = ifelse(sample_id == "50088", "500888", sample_id))

raw_sample_id_mapping_data = readxl::read_excel("../data/raw_data/validation60_15_March_2020/Cohort A NanostringAssay sample Details.xlsx") %>% janitor::clean_names() %>% 
  dplyr::select(pin, gender, vial_barcode, nanostring_sample_id, date_of_nanostring_run_12, other)

raw_clinical_data1 = readxl::read_excel("../data/raw_data/validation60_15_March_2020/cohort a survival_Hazel_21May2020.xlsx", sheet = 1) %>% janitor::clean_names() %>% 
  remove_empty("cols") %>% 
  dplyr::transmute(
    pin,gender, date_tissue_banked, 
    date_last_fup, status_last_fup, 
    stage = stage_at_bank_7th_ed,
    date_first_distant_met_post_banking,
    date_first_recurrence_post_banking,
    date_first_recurrence_post_banking_corrected = case_when(
      complete.cases(date_first_recurrence_post_banking) ~ date_first_recurrence_post_banking, 
      status_last_fup == "Alive NSR" & is.na(date_first_recurrence_post_banking) ~ date_last_fup
    ),
    age = difftime(date_tissue_banked, dob) %>% lubridate::time_length("year"))

raw_clinical_data1 %>% glimpse

## No duplicates after cleaning the clinical data
raw_clinical_data1 %>% janitor::get_dupes(pin)

ns_v60_clean_sample_data = ns_v60_raw_sample_data %>% 
  left_join(raw_sample_id_mapping_data, by = c("sample_id" = "nanostring_sample_id")) %>% 
  left_join(raw_clinical_data1, by = c("pin" = "pin", "gender" = "gender")) %>%
  as_tibble() %>% 
  dplyr::mutate(
    status_last_fup = case_when(
      pin == "41036" ~ "Alive NSR",
      TRUE ~ status_last_fup), ## 2020 June 10, email with GP and Hazel
    RFS = as.integer(difftime(date_first_recurrence_post_banking_corrected,
                              date_tissue_banked,
                              units = "days")/30),
    rfs_class = case_when(
      (RFS >= 4*12 & status_last_fup == "Alive NSR") ~ "Good",
      (RFS <= 1*12 & status_last_fup == "Dead, melanoma") ~ "Poor",
      TRUE ~ NA_character_
    ) %>% as.factor(),
    OS = as.integer(
      difftime(date_last_fup,
               date_tissue_banked,
               units = "days")/30),
    dead = ifelse(str_detect(status_last_fup, "Alive"), 0, 1),
    os_class = case_when(
      (OS >= 4*12 & status_last_fup == "Alive NSR") ~ "Good",
      (OS <= 1*12 & status_last_fup == "Dead, melanoma") ~ "Poor",
      TRUE ~ NA_character_
    ) %>% as.factor()) %>% 
  group_by(sample_id) %>% 
  dplyr::mutate(dupes_v60 = n(), 
                numbering_dupes = row_number(),
                in_mia45 = sample_id %in% colnames(list_raw_data_binary$ns),
                plot_keep = (numbering_dupes == dupes_v60) & !in_mia45) %>% 
  ungroup()

ns_v60_clean_sample_data %>% glimpse()
```


# QC check (Combined with previous 45 samples)
```{r}
ns_v60_exprs_data = log2(exprs(ns_v60_data) + 1)
rownames(ns_v60_exprs_data) = ns_feature_data$gene_name %>% 
  toupper %>%
  str_replace_all("-", "_") %>%
  str_replace_all("[.]", "_")

ns_v60_exprs_data = ns_v60_exprs_data[ns_v60_exprs_data %>% rownames %>% sort,]
```

# Save data
```{r}
save(
  ns_feature_data,
  ns_v60_clean_sample_data,
  ns_v60_exprs_data,
  file = "../data/processed_data/ns_validation60_2022_Feb_07.RData")
```

# Session Info 
```{r}
sessioninfo::session_info()
```
