---
title: "MIA - March validation 60 samples data cleaning"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Feb 16, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---


# Summary


# Loading 

## Packages

```{r}
today = format(Sys.time(), "%Y_%b_%d")
cat("This file was compiled on", today)


suppressPackageStartupMessages({
  library(tidyverse)
  library(NanoStringQCPro)
  library(survminer)
  library(survival)
  library(ggsci)
  library(janitor)
})

theme_set(theme_classic(20) +
            theme(legend.position = "bottom"))

boxplot_tbl = function(x, index = 1){
  means = apply(x, index, mean, na.rm = TRUE)
  medians = apply(x, index, median, na.rm = TRUE)
  q1 = apply(x, index, quantile, 0.25, na.rm = TRUE)
  q3 = apply(x, index, quantile, 0.75, na.rm = TRUE)
  
  tbl = tibble(
    object = as_factor(dimnames(x)[[index]]),
    means, medians, q1, q3)
  
  return(tbl)
}

```

## data
```{r}
file_version = "2020_Apr_25"
load(paste0(
  "../data/processed_data/Melanoma4_binary_",
  file_version, ".RData"
))

load(paste0(
  "../data/processed_data/Melanoma4_survival_",
  file_version, ".RData"
))

load("../data/processed_data/ns_validation60_2022_Feb_07.RData")
```


# Processing sample, feature, exprs data for NanoString (commented out to run only once)

# Running CPOP model 
```{r}
list_raw_data_binary = list_raw_data_binary %>% purrr::map(t)

list_lratio_binary = purrr::map(list_raw_data_binary, CPOP::pairwise_col_diff)

# c("CPN1", "CXCL13", "CXCR6", "CYP2J2", "CYorf15A", "DARC", "DHRS9", "DNAH2", "CXCL10", "CXCL9", "CYBB", "DCT")
```


```{r}
load("../data/processed_data/shiny_models_2021_Nov_02.RData")

ns_v60_lratio = ns_v60_exprs_data %>% t %>% CPOP::pairwise_col_diff()
```


# Introduce missing values on the genes 

```{r}
faulty_genes = c("CPN1", "CXCL13", "CXCR6", "CYP2J2", "CYorf15A", "DARC", "DHRS9", "DNAH2", "CXCL10", "CXCL9", "CYBB", "DCT") %>% toupper()

cpop_lr2genes = stringr::str_split(mia_cpop_binary$feature, "--") %>% unlist %>% unique %>% sort

gplots::venn(
  lst(faulty_genes, 
      cpop_lr2genes))

ns_v60_exprs_data_miss = t(ns_v60_exprs_data)[,colnames(list_raw_data_binary$array)]
ns_v60_exprs_data_miss[,intersect(faulty_genes, colnames(ns_v60_exprs_data_miss))] = NA

ns_v60_exprs_data_impute = CPOP::impute_cpop(cpop_result = mia_cpop_binary, 
                  x1 = list_raw_data_binary$array, 
                  x2 = list_raw_data_binary$ns, 
                  newx = ns_v60_exprs_data_miss)

ns_v60_lratio = ns_v60_exprs_data_impute %>% CPOP::pairwise_col_diff()
```



```{r}
comb_pred_tbl = mia_cpop_binary %>% 
  CPOP::predict_cpop(newz = ns_v60_lratio) %>%
  left_join(ns_v60_clean_sample_data, by = c("samples" = "file_name")) %>% 
  dplyr::mutate(
    cpop_pred = cpop_model_avg,
    cpop_prob = CPOP::expit(cpop_model_avg),
    cpop_pred_class = ifelse(cpop_model_avg > 0, "Poor", "Good"),
    dead = coalesce(dead, 0),
    miav60_median_class = case_when(
        dead == 0 & RFS > median(RFS, na.rm = TRUE) ~ "Good",
        dead == 1 & RFS <= median(RFS, na.rm = TRUE) ~ "Poor",
        TRUE ~ NA_character_)
)

table(comb_pred_tbl$cpop_pred_class)
table(comb_pred_tbl$miav60_median_class)

comb_pred_tbl %>% 
  ggplot(aes(x = CPOP::expit(cpop_model1), 
             y = CPOP::expit(cpop_model2),
             colour = rfs_class)) +
  geom_point(size = 3) +
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(slope = 1, intercept = 0, colour = "red") +
  labs(x = "Prediction from MIA - 2015, Array",
       y = "Prediction from MIA - 2018, NS")

comb_pred_tbl$cpop_pred_class %>% table

table(comb_pred_tbl$cpop_pred_class, 
      comb_pred_tbl$os_class)

fit = survfit(Surv(RFS/12, dead) ~ cpop_pred_class, 
              data = comb_pred_tbl %>% 
                dplyr::filter(plot_keep))

fit

singlemia_validate60_km = ggsurvplot(fit, pval = TRUE, 
                                     break.time.by = 2,
                                     risk.table = "nrisk_cumevents")

singlemia_validate60_km2 = singlemia_validate60_km$plot
singlemia_validate60_km3 = singlemia_validate60_km$table

library(patchwork)

singlemia_validate60_km_plots = singlemia_validate60_km2 + singlemia_validate60_km3 +
  patchwork::plot_layout(ncol = 1, byrow = FALSE, heights = c(1.5, 1))

ggsave(print(singlemia_validate60_km_plots), 
       filename = paste0("../figures/validation_60_surv_pred_", today, ".eps"),
       width = 8, height = 6)

coxph(Surv(RFS, dead) ~ cpop_pred + age, data = comb_pred_tbl)
```

```{r}
comb_pred_tbl$gender %>% table(useNA = "always")

comb_pred_tbl %>% 
  ggplot(aes(x = cpop_model_avg_prob, fill = gender)) +
  geom_density(alpha = 0.5) +
  scale_x_continuous(limits = c(0, 1))

wilcox.test(cpop_model_avg_prob ~ gender, data = comb_pred_tbl)

library(fairness)
equal_odds(
  data  = comb_pred_tbl %>% 
    dplyr::filter(complete.cases(miav60_median_class), complete.cases(gender)),
  outcome = 'miav60_median_class',
  probs   = 'cpop_model_avg_prob',
  group   = 'gender',
  cutoff  = 0.5)
```


# Session Info 
```{r}
sessioninfo::session_info()
```
